-- Referral Codes Table
-- Stores referral codes generated by users
-- Both referrer and referee get ₹25 discount
CREATE TABLE IF NOT EXISTS referral_codes (
    id UUID DEFAULT gen_random_uuid () PRIMARY KEY,
    user_id UUID NOT NULL,
    user_email TEXT NOT NULL,
    user_name TEXT,
    code VARCHAR(20) UNIQUE NOT NULL,
    discount_amount INTEGER DEFAULT 25, -- ₹25 discount for referee
    reward_amount INTEGER DEFAULT 25, -- ₹25 reward for referrer
    is_active BOOLEAN DEFAULT true,
    total_uses INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Referral Uses Table
-- Tracks when referral codes are used
CREATE TABLE IF NOT EXISTS referral_uses (
    id UUID DEFAULT gen_random_uuid () PRIMARY KEY,
    referral_code_id UUID REFERENCES referral_codes (id) ON DELETE CASCADE,
    referee_user_id UUID NOT NULL,
    referee_email TEXT NOT NULL,
    booking_id UUID,
    discount_applied INTEGER NOT NULL,
    reward_credited BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Referral Rewards Table
-- Tracks rewards earned by referrers
CREATE TABLE IF NOT EXISTS referral_rewards (
    id UUID DEFAULT gen_random_uuid () PRIMARY KEY,
    user_id UUID NOT NULL,
    user_email TEXT NOT NULL,
    amount INTEGER NOT NULL,
    referral_use_id UUID REFERENCES referral_uses (id) ON DELETE CASCADE,
    status VARCHAR(20) DEFAULT 'pending', -- pending, credited, expired
    credited_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT (NOW() + INTERVAL '90 days'),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_referral_codes_code ON referral_codes (code);

CREATE INDEX IF NOT EXISTS idx_referral_codes_user_id ON referral_codes (user_id);

CREATE INDEX IF NOT EXISTS idx_referral_uses_referee ON referral_uses (referee_user_id);

CREATE INDEX IF NOT EXISTS idx_referral_rewards_user ON referral_rewards (user_id);

CREATE INDEX IF NOT EXISTS idx_referral_rewards_status ON referral_rewards (status);

-- Enable RLS
ALTER TABLE referral_codes ENABLE ROW LEVEL SECURITY;

ALTER TABLE referral_uses ENABLE ROW LEVEL SECURITY;

ALTER TABLE referral_rewards ENABLE ROW LEVEL SECURITY;

-- RLS Policies for referral_codes
CREATE POLICY "Users can read their own referral codes" ON referral_codes FOR
SELECT USING (auth.uid () = user_id);

CREATE POLICY "Anyone can validate referral codes" ON referral_codes FOR
SELECT USING (is_active = true);

CREATE POLICY "Service role can manage referral codes" ON referral_codes FOR ALL USING (auth.role () = 'service_role');

-- RLS Policies for referral_uses
CREATE POLICY "Users can see their referral uses" ON referral_uses FOR
SELECT USING (referee_user_id = auth.uid ());

CREATE POLICY "Service role can manage referral uses" ON referral_uses FOR ALL USING (auth.role () = 'service_role');

-- RLS Policies for referral_rewards
CREATE POLICY "Users can see their rewards" ON referral_rewards FOR
SELECT USING (user_id = auth.uid ());

CREATE POLICY "Service role can manage rewards" ON referral_rewards FOR ALL USING (auth.role () = 'service_role');

-- Function to update referral code usage count
CREATE OR REPLACE FUNCTION update_referral_usage_count()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE referral_codes
    SET total_uses = total_uses + 1,
        updated_at = NOW()
    WHERE id = NEW.referral_code_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update usage count on new referral use
CREATE TRIGGER on_referral_use_insert
    AFTER INSERT ON referral_uses
    FOR EACH ROW
    EXECUTE FUNCTION update_referral_usage_count();